# Tomcat
server:
    port: 8081
    servlet:
      context-path: /drools
spring:
    # 环境 dev|test|prod
    profiles:
        active: dev
    servlet:
        multipart:
            enabled: true
            max-file-size: 100MB
            max-request-size: 100MB
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss